### ISSUE TITLE
no of classes

### ISSUE THREAD

**Issue by Vaishali-Nimilan** [Guruprasadh2509/Ground-Truth-Binary-Masking-#1]
I have a JSON file with 4 classes. I have mentioned the number of classes to be 4. I use the same annotation tool as yours
self.add_class("D00","D10","D20","D40")
TypeError: add_class() takes 4 positional arguments but 5 were given

Also I get the error,

polygons = [r['shape_attributes'] for r in a['regions'].values()]
AttributeError: 'list' object has no attribute 'values'
Thanks in advance

**Comment by Guruprasadh2509** [comment]
I actually worked on 2 classes(binary classification). In case if it is possible, could you please share me sample images may be 2, corresponding JSON file(annotated) and corresponding labels as well, I can check it.

**Comment by vaishali-77** [comment]
https://wetransfer.com/downloads/ac3c3d79a76b8b4eb9f7a1c2d8aee50920200410131846/08406ad42b18e7738c58ea16d2cc3baf20200410131846/7d92d9

Here is the link to download. Thanks

**Comment by Guruprasadh2509** [comment]
I am not able to view the annotated image, when I import the json.                                                                           
Can you try to download the annotated region data by, clicking [Annotation > Save as CSV] in the top menu bar. This will download a text file containing region shape and attribute data. Kindly do it for only the sample image which you have provided. Also kindly change the extenson to PNG from JPEG

**Comment by vaishali-77** [comment]
https://wetransfer.com/downloads/677d9e2e5e63b04458916f5869cd27be20200410161303/4e5aeab9df7287c1b473a72cdb2c293120200410161303/c774b3

I have made the following changes as mentioned by you. Here is the link. Thanks for taking the time to help!

**Comment by Guruprasadh2509** [comment]
Thank you for sharing me this file, but it is not getting worked out for me. Could you please share me the objective of annotation and on what basis the annotation is made? So that I can  try from my end and check. Thank you!

**Comment by Vaishali-Nimilan** [comment]
Thanks but I think the JSON file itself is corrupted, But thanks for trying. Could you please say some suggestions when I use more than one class, what modifications I might need to do. I could try that when I make a new JSON file.

**Comment by Guruprasadh2509** [comment]
When you ran the IPYNB file, did you get some thing like below?
Image Count: 2 #total image count
Class Count: 2#total class count in 3rd cell of jupyter notebook
  0. BG                                                
  1. Annotated label

I am trying to simulate your issue, will update you once it is completed.

**Comment by Vaishali-Nimilan** [comment]
Hey, I had the above-mentioned errors, I didn't get the image count or the total number classes when I ran the code. 
Thank you so much for trying! This code is a really useful one
If I am able to create a new JSON file and run the code for more than one class, I will get back to you.

**Comment by Guruprasadh2509** [comment]
Its my pleasure :). I referred below two links for making binary mask to work. In MRCNN library, we have visualize module, which I customized in order to save the binary mask images to local directory. I am checking the place where the needed changes need to be placed. I will keep you updated. Thank you!
https://github.com/matterport/Mask_RCNN/blob/master/mrcnn/visualize.py
https://github.com/matterport/Mask_RCNN/blob/master/samples/balloon/balloon.py

**Comment by Cipherpy** [comment]
how to modify the code for more number of classes?

**Comment by Guruprasadh2509** [comment]
@Cipherpy , I am studying the code, for making the needed changes, I came across below link, where they have used multiple classes, I am also checking the same.
https://github.com/SUYEgit/Surgery-Robot-Detection-Segmentation
"https://github.com/SUYEgit/Surgery-Robot-Detection-Segmentation/blob/master/surgery.py" has the needed changes

**Comment by Guruprasadh2509** [comment]
![image](https://user-images.githubusercontent.com/49832601/79073597-1c389480-7d05-11ea-8682-e0dfe298546f.png)
I am closing this issue, as the link(https://github.com/SUYEgit/Surgery-Robot-Detection-Segmentation/blob/master/surgery.py) has solution, Kindly refer the same.

**Comment by Vaishali-Nimilan** [comment]
Thank for the link and for the effort. I will look into it. :)

**Comment by Cipherpy** [comment]
> ![image](https://user-images.githubusercontent.com/49832601/79073597-1c389480-7d05-11ea-8682-e0dfe298546f.png)
> I am closing this issue, as the link(https://github.com/SUYEgit/Surgery-Robot-Detection-Segmentation/blob/master/surgery.py) has solution, Kindly refer the same.

Thank you for your effort
