### ISSUE TITLE
The pixel value of output mask is not 30 or 215

### ISSUE THREAD

**Issue by lackBfun** [Guruprasadh2509/Ground-Truth-Binary-Masking-#3]
Hi, thanks so much for your work. It's really helpful.
I tried your code on my own dataset, but I found that the foreground and background values within the output mask are not 215 and 30 respectively. I applied numpy.unique() to the output mask and the return value was an array like below:
[25,26,27,28,29,30,31,32,33,34,35,210,211,212,213,214,215,216,217,218,219,220]

It seems that there is something wrong with the foreground value and background value.

**Comment by Guruprasadh2509** [comment]
Hi,
Thank you for your kind words, if you can share me the sample image and corresponding annotation json file, I will be able to help you.
Kind regards
Guruprasadh
